#
# Module manifest for module 'CredMan'
#
# Generated by: Sergey Popov
#
# Generated on: 4/1/2018
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'CredMan.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# ID used to uniquely identify this module
GUID = '4c15d082-d80d-44cb-9b4b-a8767c5fb0ba'

# Author of this module
Author = 'Sergey Popov'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) 2018 Sergey Popov. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Low-level Credentials Management Cmdlets'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @(
    'Get-GenericCredential'
    'Set-GenericCredential'
    'Remove-GenericCredential'
)

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @(
            'CredManager'
            'CredentialManager'
            'Security'
        )

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/sergeypopov13/CredMan'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
